version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: auth_microservicio_p2_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices

  auth:
    image: ghcr.io/ics-pa-2025/auth_microservicio_p2:latest
    container_name: auth_microservicio_p2
    restart: unless-stopped
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL_PROD: ${FRONTEND_URL_PROD}
      FRONTEND_URL_DEV: ${FRONTEND_URL_DEV}
      SEED_RBAC: ${SEED_RBAC}
      JWT_ACCESS_EXPIRES: ${JWT_ACCESS_EXPIRES}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES}
    ports:
      - '3001:3001'
    networks:
      - microservices
volumes:
  mysql_data:
  
networks:
  microservices:
    name: safestore-microservices
    external: true
