version: '3.8'

services:
  auth:
    image: ghcr.io/ics-pa-2025/auth_microservicio_p2:latest
    container_name: auth_microservicio_p2
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    ports:
      - '3001:3001'
